### ISSUE TITLE
Run as a maven plugin but fail: something wrong with the dependency

### ISSUE THREAD

**Issue by Anjiang-Wei** [TestingResearchIllinois/iFixFlakies#1]
I used iFixFlakies just like the "NonDex", as a Maven plugin, according to your Quickstart's instruction. However, when I run testrunner, it fails with the following information:
Could not find artifact edu.illinois.cs:ifixflakies:pom:1.0.0-SNAPSHOT
[WARNING] The POM for edu.illinois.cs:ifixflakies:jar:1.0.0-SNAPSHOT is missing, no dependency information available
Could you please help me out? Should I put a JAR file somewhere beforehand? Thanks a lot!

**Comment by august782** [comment]
Hi,

Thanks for trying out iFixFlakies. Based on what you're seeing, I think you need to first build the iFixFlakies plugin by running "mvn install" in the iFixFlakies repository. Then, you should be able to use the testrunner like described in the Quickstart for the project you want to run.

On another note, if you are trying to run iFixFlakies on a fresh project, you should look into running iDFlakies (https://github.com/idflakies/iDFlakies) beforehand to detect if there are any order-dependent flaky tests. iFixFlakies relies on there being existing flaky tests (provided in the same format as outputted by iDFlakies) in the test suite.

**Comment by Anjiang-Wei** [comment]
Thanks a lot for your detailed guidance!
