### ISSUE TITLE
Testrunner not found

### ISSUE THREAD

**Issue by silenceawp** [TestingResearchIllinois/iFixFlakies#2]
I have installed the plugin and add it to the pom.xml of a project.But when I run the command "mvn testrunners:testplugin,An error"testrunner not found" was raised.What may be the reason for that?

**Comment by august782** [comment]
Thank you for your interest in iFixFlakies. First, could you share the pom.xml where you added the plugin? The plugin needs to be added under <build><plugins>; it may be possible you added it under a different part in the pom.xml.

Also, from the command you provided, it should be "mvn testrunner:testplugin" (note how it is testrunner without an "s" at the end), but I don't know if that is actual command you used or just a typo here.

**Comment by silenceawp** [comment]
Thanks for your instant reply.It turns out there is some triky things in pom.xml.I figured the problem out and can run the command "mvn testrunner.testplugin" now.I tried it on a project"https://github.com/ArangoDB-Community/arangodb-tinkerpop-provider",which is stated on second line of the list of flaky tests"https://docs.google.com/spreadsheets/d/1aeQr9Rlb1ohGTABZsd5sZLdjh0hedxAWFJxHpsCnJ1w/edit#gid=586894768".However there seem to be nothing meaningful in the stdout.And no other output files are created. 
[stdout.txt](https://github.com/TestingResearchIllinois/iFixFlakies/files/4211371/stdout.txt)

**Comment by august782** [comment]
iFixFlakies needs a passing order and a failing order to fix the order-dependent flaky test, and it uses the same format as the output of iDFlakies (https://github.com/idflakies/iDFlakies). In other words, you will need to run iDFlakies first to find the orders where it passes and fails before running iFixFlakies. We will update the instructions to clarify this point.

However, for this specific case you are looking at, it seems to be marked as SKIP in the spreadsheet, which means it is a test that should not have been run. I'm not sure if you want to focus on this specific case.

**Comment by silenceawp** [comment]
Thank you！Please show "the exact command that is needed to be used on ifixflakies after running idflakies "in your next update.I didn't notice that column and thought everything in the sheet was available

**Comment by august782** [comment]
In case you want to try it now, please first follow the instructions for running iDFlakies (https://github.com/idflakies/iDFlakies) to detect any flaky tests. If iDFlakies finds flaky tests, then follow the current instructions for running iFixFlakies (both iDFlakies and iFixFlakies require modifying the pom.xml in very similar ways; in the limit you can just "git checkout" the pom.xml and modify the pom.xml "from scratch" based on the iFixFlakies instructions.

**Comment by silenceawp** [comment]
So I don't need to use a specific command to  input the output of IDflakies to Ifixflakies?Running IDFlakies beforehand,and then use the command "mvn testrunner:testplugin" will be OKay?

**Comment by august782** [comment]
Yes, if iDFlakies detects an order-dependent flaky test, it will output the relevant data into a directory ```.dtfixingtools/``` (more specifically, it should have ```.dtfixingtools/detection-results/flaky-lists.json```). iFixFlakies uses that output to begin its fixing process.

**Comment by silenceawp** [comment]
Thank you very much!
